config/routes.rb
PredictTheSky::Application.routes.draw do

  root :to => 'subscribers#new'
  resources :subscribers, :only => [:new, :create]


end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :phonenumber

  validates :phonenumber, :uniqueness => true, :numericality => { :only_integer => true, :greater_than_or_equal_to => 12012000000, :less_than_or_equal_to => 19999999999}
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  def self.within(latitude, longitude)
    Subscriber.near([latitude, longitude], 50)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.find_or_create_by_phonenumber(params[:subscriber][:phonenumber])
    @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    @subscriber.phonenumber = params[:subscriber][:phonenumber]
    @subscriber.phonenumber = @subscriber.phonenumber.gsub(/\D/, "")  
    @address = params[:address] + ', ' + params[:city] + ', ' + params[:state] + ' ' + params[:zip]
    if (params[:address] != '')
      coords = Geocoder.coordinates(@address)
      latitude = coords[0]
      longitude = coords[1]
    else
      latitude = params[:subscriber][:latitude]
      longitude = params[:subscriber][:latitude]
    end
    @subscriber.latitude = latitude
    @subscriber.longitude = longitude
    @subscriber.zone = Timezone::Zone.new(:latlon => [latitude, longitude]).rules.last["name"]
    @subscriber.iss_event = params[:subscriber][:iss_event]
    @subscriber.iridium_event = params[:subscriber][:iridium_event]

    respond_to do |format|
      if @subscriber.save

        @client.account.sms.messages.create(
          :from => ENV['TWILIO_FROM_NUMBER'],
          :to => @subscriber.phonenumber,
          :body => 'Welcome to the Predict the Sky notification service, your time zone is ' + @subscriber.zone + '! Txt STOP to unsubscribe.'
        )
        format.html { redirect_to :root, notice: 'Subscriber was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<script>
  function success(position) {
    var lat = $('#subscriber_latitude'); 
    var lng = $('#subscriber_longitude');
    
    lat.val(position.coords.latitude);
    lng.val(position.coords.longitude);
  }

  function error(msg) {
    $('#address_field').show();
    console.log(msg);
  }
  $(document).ready(function() {
    $("#subscriber_phonenumber").keydown(function(event) {
      // Allow: backspace, delete, tab and escape
      if ( event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || 
          // Allow: Ctrl+A
         (event.keyCode == 65 && event.ctrlKey === true) || 
         // Allow: home, end, left, right
         (event.keyCode >= 35 && event.keyCode <= 39)) {
         // let it happen, don't do anything
        return;
      }
      else {
        // Ensure that it is a number and stop the keypress
        if ((event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
           event.preventDefault(); 
        }   
      }
    });
    $('#address_field').hide();
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(success, error);
    } else {
      error('not supported');
    }
  });
</script>
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phonenumber %><br />
    <%= f.text_field :phonenumber, :maxlength => 11, :size => 13, :placeholder => '12125554444' %>
  </div>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <div class="field" id="address_field">
    <label for="address">Address</label><br>
    <textarea id="address" name="address"></textarea>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Phonenumber</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.phonenumber %></td>
    <td><%= subscriber.latitude %></td>
    <td><%= subscriber.longitude %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
    <td><%= link_to 'Destroy', subscriber, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<script>
  function success(position) {
    var lat = $('#subscriber_latitude');
    var lng = $('#subscriber_longitude');

    lat.val(position.coords.latitude);
    lng.val(position.coords.longitude);
  }

  function error(msg) {
    $('#address_field').show();
    console.log(msg);
  }
  $(document).ready(function() {
    $("#subscriber_phonenumber").keydown(function(event) {
      // Allow: backspace, delete, tab and escape
      if ( event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 ||
      // Allow: Ctrl+A
      (event.keyCode == 65 && event.ctrlKey === true) ||
      // Allow: home, end, left, right
      (event.keyCode >= 35 && event.keyCode <= 39)) {
        // let it happen, don't do anything
        return;
      }
      else {
        // Ensure that it is a number and stop the keypress
        if ((event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
          event.preventDefault();
        }
      }
    });
    $('#address_field').hide();
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(success, error);
      } else {
      error('not supported');
    }
  });
</script>

<div id="pitch">
  <p> Predict the Sky SMS is a text message service for satellite enthusiasts. It tracks satellite events and sends you a SMS message when one is visible from your location on Earth as it's happening. Right now it tracks the ISS as it passes over the earth, as well as iridium flare events from a variety of satelites. It pulls the data from <a href="http://www.heavens-above.com">Heavens-Above.com</a> and uses <a href="http://twilio.com/">Twilio</a> to send the text messages to subscribers.</p>
</div><!--/pitch-->

<div id="form" class="clearfix">
  <%= form_for(@subscriber) do |f| %>
    <% if @subscriber.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

        <ul>
          <% @subscriber.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
    <ul>
      <li>
      <%= f.label :phonenumber, "Phone #:" %>
      <%= f.text_field :phonenumber, :maxlength => 11, :placeholder => '12125554444' %>
      </li>
      <div id="address_field">
        <li>
        <label>Address:</label>
        <input name="address" type="text">
        </li>
        <li>
        <label>City:</label>
        <input name="city" type="text">
        </li>
        <li>
        <label>State:</label>
        <input name="state" type="text">
        </li>
        <li>
        <label>Zip:</label>
        <input name="zip" type="text">
        </li>
      </div>
      <li>
      	<label>Subscribe to Events:</label>
		<span><%= f.label :iss_event, "ISS" %>
		<%= f.check_box :iss_event %></span>
		<span><%= f.label :iridium_event, "Iridium" %>
		<%= f.check_box :iridium_event %></span>
      </li>
      <li>
      <button type="submit">Get Notified</button>
      </li>
    </ul>
  <% end %>
</div><!--/form-->

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phonenumber:</b>
  <%= @subscriber.phonenumber %>
</p>

<p>
  <b>Latitude:</b>
  <%= @subscriber.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @subscriber.longitude %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>